- name: install correct manta version
  apt:
    name:
      - manta=3.2.0
    state: present
    update_cache: yes
    force: True
  become: yes
- name: start manta
  raw: systemctl start manta
  become: yes
