- name: node setup
  hosts: todeploy
  roles:
    - role: nodesetup
    - role: zabbix
    - role: authkeys

- name: dns
  hosts: todeploy
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: dns

- name: certs setup 
  hosts: todeploy
  roles:
    - role: certs
