- name: update apt
  raw: apt update

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ chain }}.engineering"

- name: setup manta repo
  raw: curl -o /usr/share/keyrings/manta.gpg https://deb.manta.systems/manta.gpg && curl -o /etc/apt/sources.list.d/manta.list https://deb.manta.systems/manta.list && apt update

- name: install manta
  apt:
    name:
      - manta=3.2.0
    state: present

- name: dolphin symlink fix
  raw: ln -s /usr/bin/manta /usr/bin/dolphin
  when: chain == "dolphin"

- name: dolphin rococo json fix
  raw: curl -sLo /usr/share/substrate/rococo.json https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/chain-specs/rococo.json
  when: chain == "dolphin"

- name: dolphin json fix
  raw: curl -sLo /usr/share/substrate/dolphin.json https://raw.githubusercontent.com/Manta-Network/Manta/manta/genesis/dolphin-testnet-genesis.json
  when: chain == "dolphin"

- name: start and enable "{{ chain }}" service
  raw: systemctl enable --now "{{ chain }}.service"
  ignore_errors: True

- name: install systools
  raw: apt -y install htop iftop iotop

- name: install "nginx" package
  ansible.builtin.apt:
    name: nginx
    state: present

- name: install "snapd" package
  ansible.builtin.apt:
    name: snapd
    state: present

