#for calamari

- name: Add dns entry systems
  community.aws.route53:
    state: present
    zone: "{{ chain }}.systems"
    record: "{{ inventory_hostname }}.{{ chain }}.systems"
    type: A
    ttl: 7200
    value: "{{ ansible_host }}"
    wait: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when: chain == "calamari"
  ignore_errors: yes
- wait_for:
    host: "{{ inventory_hostname }}.{{ chain }}.systems"
    port: 80
    delay: 30
  when: chain == "calamari"


#for dolphin

- name: Add dns entry engineering
  community.aws.route53:
    state: present
    zone: "{{ chain }}.engineering"
    record: "{{ inventory_hostname }}.{{ chain }}.engineering"
    type: A
    ttl: 7200
    value: "{{ ansible_host }}"
    wait: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when: chain == "dolphin"
  ignore_errors: yes
- wait_for:
    host: "{{ inventory_hostname }}.{{ chain }}.engineering"
    port: 80
    delay: 30
  when: chain == "dolphin"
