- name: Add dns entry
  community.aws.route53:
    state: present
    zone: "{{ chain }}.systems"
    record: "{{ inventory_hostname }}.{{ chain }}.systems"
    type: A
    ttl: 7200
    value: "{{ ansible_host }}"
    wait: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

- wait_for:
    host: "{{ inventory_hostname }}.{{ chain }}.systems"
    port: 80
    delay: 30
